### ISSUE TITLE
Question: Can you provide promised documentation?

### ISSUE THREAD

**Issue by alexwpete** [ColdFireHunter/MAX22530-arduino#1]
Can you please provide the promised documentation that you have for this? I'd like to see how you implemented and initialized the communication of this chip on arduino. Alternatively, if you can publish a repo of an arduino project that utilizes this source code, I could see how you initialized the SPI communication.

I really appreciate any help you can provide.

**Comment by ColdFireHunter** [comment]
I'm sorry I did not get to it yet.
I will add it in the next 24 hours.
If you then have any further questions please ask them.

**Comment by ColdFireHunter** [comment]
On what platform are you using this libary. Because it currently only workes on STM32
I need to rewrite it for other platform.
Please be patient.

**Comment by alexwpete** [comment]
Hello. No need to rewrite it because the STM32 is fine. I just wanted to see if you had documentation already prepared.
